FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias Python
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de Flask
COPY . .

EXPOSE 5000
CMD ["python", "Gestion_de_notificaciones.py"]
